print("Halo selamat datang di bioskop!")
print("Dimanakah kamu ingin menonton?")
print("1) XXI Empire")
print("2) XXI amplaz")
print("3) XXI JCM")
int(input("masukan pilihan anda:"))
print("Mau nonton film apa nih?ada film:")
print("1. Frozen")
print("2. keramat")
print("3. KKN di desa penari")
int(input("pilih nomor film:"))
print("Mau nonton layar bioskop apa:")
print("1. reguler")
print("2. dolby amos")
print("3. premiere")

def tempat():
    print("Dimanakah kamu ingin menonton?")
    print("1) XXI Empire")
    print("2) XXI amplaz")
    print("3) XXI JCM")



TEMPAT=int(input("masukan pilihan anda:"))